formulas:
  - bash
  - cmake
  - cmark-gfm
  - coreutils
  - curl
  - difftastic
  - diffutils
  - emacs
  - enchant
  - figlet
  - findutils
  - fzf
  - gawk
  - gcc
  - gh
  - git
  - gnu-sed
  - grep
  - mas
  - make
  - mise
  - openssh
  - pkgconf
  - source-highlight
  - starship
  - tmux
  - tree
  - unzip
  - wget
  - ykman

casks:
  - alfred
  - drawio
  - figma
  - font-fira-code
  - font-fira-code-nerd-font
  - ghostty
  - gitify
  - google-analytics-opt-out
  - google-chrome
  - google-drive
  - google-japanese-ime
  - gpg-suite-no-mail
  - keybase
  - maccy
  - orbstack
  - slack
  - yubico-authenticator
  - zoom
