---
- name: Be sure brew is installed
  block:
  - name: Check whether brew is installed
    command: type brew
    register: brew_status
    failed_when: brew_status.rc not in [0, 1]
    changed_when: false
    check_mode: no

- name: Be sure brew prerequirements are installed
  shell: xcode-select --install 2>&1 | grep -q "already installed"

- name: Run brew install script
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_status.rc > 0


- name: Be sure homebrew is updated
  homebrew:
    update_homebrew: yes


- name: Be sure homebrew formulas are installed
  homebrew:
    name: "{{ formulas }}"
    state: present


- name: Be sure homebrew casks are installed
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=/Applications"
    accept_external_apps: yes
  loop: "{{ casks }}"
  ignore_errors: yes
