---
- name: Be sure variables are loaded
  include_vars: bun.yaml

- name: Be sure bun is installed
  block:
    - name: Check whether bun is installed
      command: type bun
      register: bun_status
      failed_when: bun_status.rc not in [0, 1]
      changed_when: false
      check_mode: no

    - name: Run bun install script
      shell: /bin/bash -c "$(curl -fsSL https://bun.sh/install)"
      when: bun_status.rc > 0

- name: Be sure bun packages are installed
  shell: bun add -g "{{ item}}"
  loop: "{{ packages }}"
